--DB dbTest3
CREATE SCHEMA `dbTest3` ;

USE dbTest3;

--Users Table

CREATE TABLE IF NOT EXISTS Users (
userId INT AUTO_INCREMENT, 
userName VARCHAR(50) NOT NULL, 
user VARCHAR(30) NOT NULL,
pass VARCHAR(50) NOT NULL, 
age TINYINT UNSIGNED NOT NULL, 
PRIMARY KEY(userId));

--Cards Table

CREATE TABLE IF NOT EXISTS Cards (
cardId INT NOT NULL AUTO_INCREMENT, 
userId INT NOT NULL,
cNumber INT UNIQUE, 
validDate DATE, 
secCode TINYINT, 
PRIMARY KEY (cardId), 
FOREIGN KEY (userId) REFERENCES Users(userId));

